CREATE TABLE IF NOT EXISTS tokens (
    hash VARBINARY(255) PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expiry TIMESTAMP(0) NOT NULL,
    scope TEXT NOT NULL
);